on:
  schedule:
    - cron: '*/60 * * * *' # every 60 minutes

jobs:
  increment-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -al
      - run: chmod +x increment.sh
      - run: ./increment.sh